prompt_order = [
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_state",
    "cmd_duration",
    "line_break",
    "character"
]

# Don't print a new line at the start of the prompt
add_newline = false

[character]      # The name of the module we are configuring is "character"
#symbol = "➜ "     # The "symbol" segment is being set to "➜"
#symbol = "λ"
symbol = "$"
vicmd_symbol = "✓"
